name: MasonBootTest
type: container
profiles:
  - default

source:
  type: image
  mode: pull
  protocol: simplestreams
  server: https://cloud-images.ubuntu.com/releases
  alias: "24.04"

config:
  user.user-data: |
    #cloud-config
    packages:
      - git
      - python3
      - python3-pip  

    runcmd:
     
      - [ git, clone, "https://github.com/MasonGillDev/BootStapTest.git", "/root/my-bootstraps" ]

      
      - [ chmod, "+x", "/root/my-bootstraps/bootstrap.sh" ]

      
      - [ bash, "-c", "/root/my-bootstraps/bootstrap.sh | tee -a /var/log/my-bootstrap.log" ]
